### PR TITLE
fix: resolve an issue where Grbl controller cannot recognize certain startup message

### PR DESCRIPTION
**Pull request by cheton**
This issue was reported on FB where some users may experience startup problems when using a custom Grbl firmware with certain startup message (e.g. `Grbl 1.1h: LongMill build ['$' for help]`):

image

I changed the strict regular expression from 

```
/^([a-zA-Z0-9]+)\s+((?:\d+\.){1,2}\d+[a-zA-Z0-9\-\.]*)\s+(\[[^\]]+\])/
```
to 

```
/^([a-zA-Z0-9]+)\s+((?:\d+\.){1,2}\d+[a-zA-Z0-9\-\.]*)([^\[]*\[[^\]]+\].*)?/
```

so it can math the string `Grbl 1.1h: LongMill build ['$' for help]`

### CODE REVIEW

**Comment by falviani** [comment]
I am expecting to get one of the new controllers in the near future. When I
do, I'll let you know what we've got (it should still be 1.1h).

-Frank

**Comment by MitchBradley** [comment]
These instructions tell how to deploy new LongMill firmware: https://sienci.com/dmx-longmill/grbl-firmware/

**Comment by cheton** [comment]
I made a slight change to the code to increase the flexibility:

```
/^([a-zA-Z0-9]+)\s+((?:\d+\.){1,2}\d+[a-zA-Z0-9\-\.]*)([^\[]*\[[^\]]+\].*)?/
```

It will get the exact `firmware` and `version` from the startup message, and the rest is optional.

**Comment by cheton** [comment]
Fixed in [1.9.21](https://github.com/cncjs/cncjs/releases/tag/v1.9.21)

**Comment by falviani** [comment]
I still have my original controller with the problematic version string. I
tested 1.9.21 this morning and it works fine.

**Comment by etx** [comment]
Fixed my issues on the Millright Mega V controller also. Thanks a million!!!

**Pull request merged**
