### PR TITLE
Enhance CI/CD workflow with Yarn 3, Node.js 14, and GitHub Actions

### PR DESCRIPTION
**Pull request by emcniece**
Generates an [npm-shrinkwrap.json](https://docs.npmjs.com/cli/v9/commands/npm-shrinkwrap) file during releases, adds it to Appveyor artifacts where it will live for 1 month post-CI-run, and hopefully deploys it to Github releases.

We'll test this in an upcoming tag where we include https://github.com/cncjs/cncjs/pull/796.

Resolves https://github.com/cncjs/cncjs/issues/794.

### CODE REVIEW

**Comment by cheton** [comment]
I suggest including the lock files 'package-lock.json' or 'yarn.lock' in the repository by removing them from the '.gitignore' file. What are your thoughts on this?

**Comment by emcniece** [comment]
Including package-lock.json is a good idea, yes! It is intended to be committed to VCS. I am unsure about the variance in development platforms however.

During the CI runs for this PR I extracted npm-shrinkwrap.json and performed a diff between Linux, Mac, and Windows builds. There are many changes between each platform, mostly package signatures such as:

```
<       "resolved": "https://registry.npmjs.org/fd-slicer/-/fd-slicer-1.1.0.tgz",
<       "integrity": "sha512-cE1qsB/VwyQozZ+q1dGxR8LBYNZeofhEdUNGSMbQD3Gw2lAzX9Zb3uIU6Ebc/Fmyjo9AWWfnn0AUCHqtevs/8g==",
31144,31145d26064
<       "resolved": "https://registry.npmjs.org/yeast/-/yeast-0.1.2.tgz",
<       "integrity": "sha512-8HFIh676uyGYP6wP13R/j6OJ/1HwJ46snpvzE7aHAN3Ryqh2yX6Xox2B4CUmTwwOIzlG3Bs7ocsP5dZH/R1Qbg==",
31150,31151d26068
<       "resolved": "https://registry.npmjs.org/yn/-/yn-3.1.1.tgz",
<       "integrity": "sha512-Ux4ygGWsu2c7isFWe8Yu1YluJmqVhxqK2cLXNQA5AcC3QfbGNpM7fu0Y8b/z16pXLnFxZYvWhd3fhBY9DLmC6Q==",
```

There are however also specific package differences (I assume for the included binaries) such as:

```
>     "node_modules/watchpack/node_modules/fsevents": {
>       "version": "2.3.2",
>       "dev": true,
>       "license": "MIT",
>       "optional": true,
>       "os": [
>         "darwin"
>       ],
>       "engines": {
>         "node": "^8.16.0 || ^10.6.0 || >=11.0.0"
>       }
>     },
```

This leads me to think that package-lock.json will differ between OS builds, and since the community here has contributors from many platforms we could see frequent changes to package-lock.json that revert previous changes.

Perhaps this won't cause any problems. If it does become an issue, we could explore a unified development environment in a Docker container or something. 

This PR currently provides evidence of package versions in a given CI run, which satisfies the original ask. I'm ok with either option, adding package-lock.json or continuing to ignore it. Your preference?

**Comment by colin-campbell** [comment]
The first question should maybe be npm or yarn? It shouldn't really be npm for development and yarn for CI. 
If yarn is used, shrinkwrap is kinda redundant. In fact running `npm ci` or `yarn --frozen-lock-file` from a tagged version gives you a canonical install without shrinkwrap at all.

**Comment by parachvte** [comment]
Reading through the [npm shrinkwrap doc](https://docs.npmjs.com/cli/v9/configuring-npm/npm-shrinkwrap-json).

When the library is a global commend line tool / dev dependency, you will want to lock down dep versions to make it stable as possible. In case of cncjs, it's a desktop application, in most cases users won't need the published `npm-shrinkwrap.json`. `package-lock.json` or `yarn.lock` is more useful for developers.

**Comment by cheton** [comment]
I intend to use Yarn as the package manager, as I am familiar with it and have used it extensively on recent projects."

I will perform a test in a separate branch (`feature/next`) for both Yarn and Node.js upgrade. If everything works as expected, I will update the pull request with the change.

**Comment by cheton** [comment]
Both Yarn 3 and Node.js 14 have been successfully upgraded. The build results can be viewed at the following link: https://ci.appveyor.com/project/cheton/cncjs/builds/45970962.

In addition, I plan to create a new pull request to migrate the CI pipeline from AppVeyor to GitHub actions for further efficiency.

**Review by cheton — APPROVED** [review]

**Comment by emcniece** [comment]
Impressive work @cheton 🚀

**Comment by cheton** [comment]
Published [v1.10.0](https://github.com/cncjs/cncjs/releases/tag/v1.10.0) 🚀

**Pull request merged**
