### PR TITLE
[Feeder][Sender] Add global variables support

### PR DESCRIPTION
**Pull request by cheton**

### CODE REVIEW

**Comment by cheton** [comment]
Hi @scottlaird

With this PR, you will be able to declare global variables using the `global` object. Otherwise, it will be a local scope variable.

To store the value of the previous tool number, you can do something like that:

```gcode
%unloadtool = Number(global.prevtool) || 0
%loadtool = tool
%global.prevtool = loadtool
```

This change will be available in CNCjs 1.9.18 release.

**Comment by scottlaird** [comment]
Thanks!

**Comment by neilferreri** [comment]
@cheton This is really cool!

**Comment by cheton** [comment]
@scottlaird @neilferreri 

The support for primitive types (`Boolean`, `Number`, `Object`, `String`) and a global variable (`JSON`) are also included in this PR.

You can create a macro like this:

```gcode
%global.state.x=10
%global.state.y=20
%global.state.z=30
%global.tool = tool
(global=[JSON.stringify(global)])
```

The inline comment will be displayed on the console that allows you to trace the result:
```
feeder> (global={"state":{"x":10,"y":20,"z":30},"tool":0})
```

**Pull request merged**
