### PR TITLE
Add event triggers to M0, M1, and M6 commands

### PR DESCRIPTION
**Pull request by carlos-sarmiento**
I've added an event trigger to M0, M1 and M6 commands so that a event defined on the settings would be triggered when these commands are run.

If people agree that we should make the change I'll add it to the other controllers to keep behavior consistent

### CODE REVIEW

**Comment by carlos-sarmiento** [comment]
I'm seeing activity on the repo. Is there any interest in this PR?

**Comment by cheton** [comment]
Hi @carlos-sarmiento 
It looks good to me. I will add support to other controllers using the same PR.

**Review by cheton — APPROVED** [review]

**Comment by carlos-sarmiento** [comment]
Any additional change we need to do to get the PR merged?

**Comment by joeogro** [comment]
I need CNCjs 1.9.22 , can someone provide me please?

**Pull request merged**
