### PR TITLE
Propagate line comments in GRBL M0/M1/M6 commands to UI dialog

### LINKED ISSUE #467: Feature Request, custom text in M0 / M1 dialogues
#### Description

Feature Request, custom text in M0 / M1 dialogues.

I am using a tool change macro that has an M0 and a few M1 commands in to pause the program whilst I do the usual things like changing the tool, attaching the problem, removing the probe etc.

It would be great if I could have the dialogue box tell me what to do at each stage. At the moment it says "M0 Program Pause", "click the Continue button to resume execution". I'd like to be able to add an additional block of text after that, e.g "Connect the probe wire and position the probe"

I think the best place to put this text in the macro would be as a comment on the line before the M0 / M1. e.g.

```
(Connect the probe wire and position the probe)
M0

```

This could also then expand to the M6 manual tool change command to tell you which tool to fit. At the moment it just says "**M6 Tool Change**", "Run a tool change macro to change the tool and adjust the Z-axis offset. Afterwards click the resume button to resume program execution."

I tend to use Carbide Create for generating the majority of my gcode, and it looks like this:

```
(TOOL/MILL,0.2000,0,1.0000,15.0)
M6 T18

```

So from that it gives a bit of info about the tool as well as the actual tool number.

So the prompt for that could include the tool number in the title, e.g. "**M6 Tool Change: Tool T18**", and then the additional text after the other text in a new paragraph, e.g. "TOOL/MILL,0.2000,0,1.0000,15.0", which although cryptic does remind me what tool 18 is.

I guess I could actually number all the tools the same as Carbide Create does, but displaying the Tool number would still be really good for that.

#### Versions

- CNCjs: 1.9.18
- Node.js: 6.x
- NPM: 5.x

#### How Do You Install CNCjs?

- [x] NPM
- [ ] Download the CNCjs Desktop Application

#### CNC Controller

- [x] Grbl
- [ ] Smoothieware
- [ ] TinyG/g2core

#### Hardware

- [x] Raspberry Pi
- [ ] Desktop or Laptop
- [ ] Mobile Device

#### Operating System

- [x] Not Applicable
- [ ] Windows
- [ ] Mac
- [ ] Linux

### PR DESCRIPTION
**Pull request by colincross**
Capture any line comment (everything after a semicolon) on an M0, M1
or M6 command and display is as part of the pause dialog in the UI.

Fixes #467.

### CODE REVIEW

**Comment by cheton** [comment]
It looks good to me. I will add this feature to other controllers as well.

**Review by cheton — APPROVED** [review]

**Comment by cheton** [comment]
Hi @colincross,

I modified your PR to display the whole line when entering the `Hold` state. Now it can display any comment format either using semi-colons or brackets:

```nc
; Comment
(Comment)
```

image

image

image

**Comment by neilferreri** [comment]
This looks awesome guys!
@cheton Welcome back!

**Review by cheton — APPROVED** [review]

**Comment by wb9tpg** [comment]
It only works on a macro for me.  If I embed the same Gcode in a file it does not display the comment.

**Comment by cheton** [comment]
Published [v1.9.26](https://github.com/cncjs/cncjs/releases/tag/v1.9.26)

**Pull request merged**
