### PR TITLE
Translation to Dutch

### PR DESCRIPTION
**Pull request by dutchpatriot**
Translated all the resource files: https://github.com/cncjs/cncjs/tree/master/src/web/i18n/nl

### CODE REVIEW

**Comment by dutchpatriot** [comment]
Conflicts are resolved already code in github doesn't give any red stuff anymore and I added the new addition translations for the  M0, M1, M2, M30, M6 commands also.

**Comment by cheton** [comment]
Hi @dutchpatriot ,

There are new strings that need to translate. Could you help translate the followings to Dutch? Thanks.

https://github.com/cncjs/cncjs/blob/master/src/web/i18n/nl/resource.json#L142
https://github.com/cncjs/cncjs/blob/master/src/web/i18n/nl/resource.json#L144
https://github.com/cncjs/cncjs/blob/master/src/web/i18n/nl/resource.json#L445

You can update it here:
```json
"Click the Continue button to resume execution.": "",
"Continue": "",
"Resume": "",
```

**Comment by dutchpatriot** [comment]
2017-10-06 12:36 GMT+02:00 Cheton Wu <notifications@github.com>:

**Comment by dutchpatriot** [comment]
Done...

Grts
Dutchpatritot
Marco van Kekem


2017-10-07 13:10 GMT+02:00 Marco van <dutchpatriot@gmail.com>:

**Pull request merged**
