### PR TITLE
feat(Grbl): support UART communication without resetting the connection upon opening

### PR DESCRIPTION
**Pull request by cheton**
### **PR Type**
enhancement

___

### **Description**
- Enhanced the Grbl controller to support UART communication without resetting the connection upon opening.
- Added logic to handle scenarios where a startup message is not received, ensuring the controller is marked as ready and initialized.
- Introduced a throttled `queryActivity` function to periodically send status queries when the connection is open.
- Improved the initialization process by checking and setting `ready` and `initialized` flags appropriately.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>GrblController.js</strong><dd><code>Enhance UART communication handling and initialization logic</code></dd></summary>
<hr>

src/server/controllers/Grbl/GrblController.js

<li>Added handling for UART communication without startup message.<br> <li> Introduced <code>queryActivity</code> function with throttling.<br> <li> Improved initialization checks for <code>ready</code> and <code>initialized</code> states.<br> <li> Enhanced status report querying logic.<br>

</details>

  </td>
  <td><a href="https://github.com/cncjs/cncjs/pull/880/files#diff-4dacbcae20bbf70f0461da55cad9e5a4315835c0150c2f99d6f99bf626afa28a">+32/-5</a>&nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by cheton** [comment]
Hi @MitchBradley,

It seems to be working as expected: https://github.com/cncjs/cncjs/issues/868#issuecomment-2403738690

Would you have time to review the changes? Thanks!

**Comment by MitchBradley** [comment]
I will test it tomorrow.

**Review by MitchBradley — APPROVED** [review]
It passed my tests

**Comment by cheton** [comment]
Thank you for confirming. I'll create a new release for the change.

**Pull request merged**
